version: "3.4"

services:

  setup_s3_bucket:
    image: marcellodesales/terraform-setup-s3-bucket
    build: .
    volumes:
      - ${HOME}/.aws:/root/.aws
    environment:
      - USE_LOCAL_CONFIG=true
      - BUCKET_NAME=${BUCKET_NAME:-terraform-state-supercash.example.com}
      - BUCKET_DEPLOYER_USER=${BUCKET_DEPLOYER_USER:-terraform-deployer}
